//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba21
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ДолжнСотр.
    /// </summary>
    // *** Start programmer edit section *** (ДолжнСотр CustomAttributes)

    // *** End programmer edit section *** (ДолжнСотр CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжнСотрE", new string[] {
            "IDДолжности as \'I d должности\'",
            "Должность as \'Должность\'"})]
    [View("ДолжнСотрL", new string[] {
            "IDДолжности as \'I d должности\'",
            "Должность as \'Должность\'"})]
    public class ДолжнСотр : ICSSoft.STORMNET.DataObject
    {
        
        private int fIDДолжности;
        
        private string fДолжность;
        
        // *** Start programmer edit section *** (ДолжнСотр CustomMembers)

        // *** End programmer edit section *** (ДолжнСотр CustomMembers)

        
        /// <summary>
        /// IDДолжности.
        /// </summary>
        // *** Start programmer edit section *** (ДолжнСотр.IDДолжности CustomAttributes)

        // *** End programmer edit section *** (ДолжнСотр.IDДолжности CustomAttributes)
        public virtual int IDДолжности
        {
            get
            {
                // *** Start programmer edit section *** (ДолжнСотр.IDДолжности Get start)

                // *** End programmer edit section *** (ДолжнСотр.IDДолжности Get start)
                int result = this.fIDДолжности;
                // *** Start programmer edit section *** (ДолжнСотр.IDДолжности Get end)

                // *** End programmer edit section *** (ДолжнСотр.IDДолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДолжнСотр.IDДолжности Set start)

                // *** End programmer edit section *** (ДолжнСотр.IDДолжности Set start)
                this.fIDДолжности = value;
                // *** Start programmer edit section *** (ДолжнСотр.IDДолжности Set end)

                // *** End programmer edit section *** (ДолжнСотр.IDДолжности Set end)
            }
        }
        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (ДолжнСотр.Должность CustomAttributes)

        // *** End programmer edit section *** (ДолжнСотр.Должность CustomAttributes)
        [StrLen(255)]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (ДолжнСотр.Должность Get start)

                // *** End programmer edit section *** (ДолжнСотр.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (ДолжнСотр.Должность Get end)

                // *** End programmer edit section *** (ДолжнСотр.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДолжнСотр.Должность Set start)

                // *** End programmer edit section *** (ДолжнСотр.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (ДолжнСотр.Должность Set end)

                // *** End programmer edit section *** (ДолжнСотр.Должность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжнСотрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжнСотрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжнСотрE", typeof(IIS.Proba21.ДолжнСотр));
                }
            }
            
            /// <summary>
            /// "ДолжнСотрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжнСотрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжнСотрL", typeof(IIS.Proba21.ДолжнСотр));
                }
            }
        }
    }
}
